name: release

on:
    workflow_dispatch:
        inputs:
            dry-run:
                description: "Use dry-run"
                required: false
                type: boolean
                default: false
            run-id:
                description: "Build workflow run ID"
                required: true
                type: string
            only-publish-to:
                description: "Only publish packages to"
                required: false
                type: choice
                default: GitHub
                options:
                    - GitHub
            run-name:
                description: "Run name"
                required: false
                type: string

run-name: "${{ inputs.run-name }} Release | ${{ inputs.only-publish-to }} ${{inputs.dry-run && '| Dry Run ' || ''}}| Build from #${{ inputs.run-id }}"
concurrency:
    group: ${{ github.workflow }}-${{ inputs.run-id }}
    cancel-in-progress: false

jobs:
    meta:
        uses: ./.github/workflows/meta.yml
        with:
            reuse-from-run-id: ${{ inputs.run-id }}

    changelog:
        name: Generate changelog
        needs: meta
        runs-on: ubuntu-latest
        outputs:
            release_body: ${{ steps.git-cliff.outputs.content }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Generate a changelog
              uses: orhun/git-cliff-action@v4
              id: git-cliff
              with:
                  config: .github/cliff.toml
                  args: >-
                      -vv --latest --strip header
                      ${{ needs.meta.outputs.is-prerelease == 'false' && '--tag-pattern "^v[0-9]+\\.[0-9]+\\.[0-9]+$"' || '' }}
              env:
                  OUTPUT: CHANGES.md
                  GITHUB_REPO: ${{ github.repository }}

    github:
        needs: [meta, changelog]
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: dawidd6/action-download-artifact@v6
              with:
                  workflow: build.yml
                  run_id: ${{ inputs.run-id }}
                  name_is_regexp: true
                  name: MAA-*
                  path: assets
                  check_artifacts: true
                  if_no_artifact_found: fail

            - name: Package artifacts
              run: |
                  cd assets
                  for f in *; do
                    (cd $f && zip -r ../$f-${{ needs.meta.outputs.tag }}.zip .)
                  done

            - id: publish
              uses: softprops/action-gh-release@v2
              with:
                  files: assets/*.zip
                  tag_name: ${{ inputs.dry-run && 'v0.0.0' || needs.meta.outputs.tag }}
                  prerelease: ${{ needs.meta.outputs.is-prerelease == 'true' }}
                  body: ${{ needs.changelog.outputs.release_body }}
